package com.ignis.runtime;

import com.ignis.core.Game;
import com.ignis.core.GameObject;
import com.ignis.core.IgnisProjectIO;
import com.ignis.core.PrefabManager;
import com.ignis.core.Project;
import com.ignis.core.Scene;
import com.ignis.core.ScriptManager;
import org.json.JSONObject;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import java.awt.Dimension;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.File;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;

/**
 * Standalone game runtime — the entry point of distributions generated by the Builder.
 *
 * Unlike the Editor, this class loads a .ignis project and immediately starts
 * the world simulation (play mode) inside a plain game window, with all editor
 * visuals (grid, gizmos, colliders, editor camera) disabled.
 *
 * Startup resolution order for the project file:
 * 1. args[0] — explicit path to a .ignis file
 * 2. runtime.json in the working directory (generated by the Builder)
 *
 * runtime.json format:
 * {
 *   "project":    "projects/MyGame/MyGame.ignis",
 *   "title":      "MyGame",
 *   "width":      1280,
 *   "height":     720,
 *   "fullscreen": false
 * }
 */
public class GameRuntime {

    public static final String RUNTIME_CONFIG_FILE = "runtime.json";

    private GameRuntime() {
    }

    public static void main(String[] args) {
        try {
            RuntimeConfig config = resolveConfig(args);
            SwingUtilities.invokeLater(() -> {
                try {
                    launch(config);
                } catch (Exception e) {
                    fail("Failed to start game: " + e.getMessage(), e);
                }
            });
        } catch (Exception e) {
            fail("Failed to load runtime configuration: " + e.getMessage(), e);
        }
    }

    /** Runtime window/project configuration. */
    public static class RuntimeConfig {
        public File ignisFile;
        public String title = "Ignis Game";
        public int width = 1280;
        public int height = 720;
        public boolean fullscreen = false;
    }

    private static RuntimeConfig resolveConfig(String[] args) throws Exception {
        RuntimeConfig config = new RuntimeConfig();

        if (args.length > 0) {
            config.ignisFile = new File(args[0]);
        }

        File configFile = new File(RUNTIME_CONFIG_FILE);
        if (configFile.exists()) {
            String raw = new String(Files.readAllBytes(configFile.toPath()), StandardCharsets.UTF_8);
            JSONObject json = new JSONObject(raw);
            if (config.ignisFile == null && json.has("project")) {
                config.ignisFile = new File(json.getString("project"));
            }
            config.title = json.optString("title", config.title);
            config.width = json.optInt("width", config.width);
            config.height = json.optInt("height", config.height);
            config.fullscreen = json.optBoolean("fullscreen", config.fullscreen);
        }

        if (config.ignisFile == null) {
            throw new IllegalStateException(
                    "No project specified. Pass the .ignis path as argument or provide " + RUNTIME_CONFIG_FILE);
        }
        if (!config.ignisFile.exists()) {
            throw new IllegalStateException("Project file not found: " + config.ignisFile.getAbsolutePath());
        }
        return config;
    }

    private static void launch(RuntimeConfig config) throws Exception {
        Game game = new Game();

        // Disable editor-only visuals before anything renders
        game.setEditorCameraMode(false);
        game.setShowGrid(false);
        game.setShowColliders(false);

        // Load project and populate the world
        Project project = IgnisProjectIO.load(config.ignisFile, game);
        game.clearEntities();
        Scene scene = project.getCurrentScene();
        if (scene != null) {
            for (GameObject entity : scene.getEntities()) {
                game.addEntity(entity);
            }
        }
        game.refreshColliders();

        // Wire script and prefab managers against the project folder
        File projectFolder = IgnisProjectIO.getProjectFolder(config.ignisFile);
        ScriptManager scriptManager = new ScriptManager(projectFolder);
        game.setScriptManager(scriptManager);
        game.setPrefabManager(new PrefabManager(projectFolder, game, scriptManager));

        // Game window
        String title = (config.title != null && !config.title.isEmpty())
                ? config.title
                : project.getProjectName();
        JFrame frame = new JFrame(title);
        com.ignis.core.AppIconHelper.setWindowIcon(frame);
        frame.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        frame.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                shutdown(game, frame);
            }
        });

        game.setPreferredSize(new Dimension(config.width, config.height));
        frame.add(game);
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.setResizable(true);

        if (config.fullscreen) {
            GraphicsDevice device = GraphicsEnvironment
                    .getLocalGraphicsEnvironment()
                    .getDefaultScreenDevice();
            if (device.isFullScreenSupported()) {
                frame.setUndecorated(true);
                device.setFullScreenWindow(frame);
            } else {
                frame.setExtendedState(JFrame.MAXIMIZED_BOTH);
            }
        }

        frame.setVisible(true);
        game.requestFocusInWindow();

        // Start simulation: compiles scripts, initializes them and enters PLAYING state
        game.playWorld();
        game.start();
    }

    /**
     * Orderly shutdown: stops the game loop and audio off the EDT, then exits.
     * A watchdog guarantees the process dies even if a resource hangs, so no
     * orphan process is ever left behind.
     */
    private static void shutdown(Game game, JFrame frame) {
        frame.setVisible(false);
        frame.dispose();

        Thread watchdog = new Thread(() -> {
            try {
                Thread.sleep(5000);
            } catch (InterruptedException ignored) {
                return;
            }
            Runtime.getRuntime().halt(0);
        }, "IgnisShutdownWatchdog");
        watchdog.setDaemon(true);
        watchdog.start();

        Thread shutdownThread = new Thread(() -> {
            try {
                game.stop();
                com.ignis.core.IgnisSoundEngine.getInstance().shutdown();
            } finally {
                System.exit(0);
            }
        }, "IgnisShutdown");
        shutdownThread.start();
    }

    private static void fail(String message, Exception cause) {
        if (cause != null) {
            cause.printStackTrace();
        }
        try {
            JOptionPane.showMessageDialog(null, message, "Ignis Runtime", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ignored) {
            // Headless or UI failure — message already on stderr
        }
        System.exit(1);
    }
}
