package com.ignis.builder;

import org.json.JSONArray;
import org.json.JSONObject;

import java.io.File;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Native build strategy — exports the project as a compilable C++ project
 * for platforms without JVM support (Xbox, PlayStation, Nintendo Switch).
 *
 * The export performs three steps:
 * 1. Converts the project structures (scenes/entities) read from the .ignis
 *    file into generated C++ data headers (intermediate code).
 * 2. Copies game content (assets, scripts, scenes, data) into export/ as
 *    engine-agnostic intermediate data.
 * 3. Generates a CMake-based C++ project skeleton with a per-console
 *    platform/ integration point for proprietary SDKs.
 *
 * Console SDKs are proprietary and cannot be redistributed, so the generated
 * project compiles a portable core and documents where each SDK plugs in.
 */
public class CppExportStrategy implements BuildStrategy {

    @Override
    public BuildResult build(BuildRequest request, BuildTarget target, BuildLogger log) {
        long start = System.currentTimeMillis();
        try {
            BuildConfig config = request.getConfig();
            String gameName = config.getSafeGameName();

            File targetDir = new File(request.getBuildRoot(), target.id());
            File appDir = new File(targetDir, gameName + "-cpp");
            log.log("Preparing C++ export folder: " + appDir.getAbsolutePath());
            BuildIO.deleteDirectory(appDir);
            java.nio.file.Files.createDirectories(appDir.toPath());

            // 1. Intermediate code: scenes converted to C++ data headers
            log.log("Converting project structures to C++ (intermediate code)...");
            String projectJsonText = BuildIO.readZipEntryText(request.getIgnisFile(), "project.json");
            JSONObject projectJson = projectJsonText != null ? new JSONObject(projectJsonText) : new JSONObject();
            String sceneHeader = generateSceneHeader(request, projectJson, config);
            BuildIO.writeString(new File(appDir, "generated/scene_data.h"), sceneHeader);

            // 2. Intermediate data: full game content for the native runtime to consume
            log.log("Exporting game content to export/ ...");
            File projectFolder = new File(request.getProjectMainFolder(), "project");
            if (projectFolder.isDirectory()) {
                BuildIO.copyDirectory(projectFolder, new File(appDir, "export"), new HashSet<>());
            }

            // 3. C++ project skeleton
            log.log("Generating C++ project (CMake + sources)...");
            BuildIO.writeString(new File(appDir, "CMakeLists.txt"), cmakeLists(gameName));
            BuildIO.writeString(new File(appDir, "src/ignis_runtime.hpp"), runtimeHeader());
            BuildIO.writeString(new File(appDir, "src/ignis_runtime.cpp"), runtimeSource());
            BuildIO.writeString(new File(appDir, "src/main.cpp"), mainSource(gameName));

            // 4. Console SDK integration point
            BuildIO.writeString(new File(appDir, "platform/" + target.id() + "/README.md"),
                    platformReadme(target));

            log.log("Done: " + target.getDisplayName() + " (C++ export)");
            return BuildResult.ok(target, appDir, System.currentTimeMillis() - start);

        } catch (Exception e) {
            log.error(target.getDisplayName() + ": " + e.getMessage());
            return BuildResult.fail(target, e.getMessage(), System.currentTimeMillis() - start);
        }
    }

    // ==================== INTERMEDIATE CODE GENERATION ====================

    private String generateSceneHeader(BuildRequest request, JSONObject projectJson, BuildConfig config)
            throws Exception {
        StringBuilder sb = new StringBuilder();
        sb.append("// Generated by IgnisEngine Builder - DO NOT EDIT\n");
        sb.append("// Intermediate representation of the project scenes.\n");
        sb.append("#pragma once\n\n");
        sb.append("namespace ignis {\n\n");

        sb.append("constexpr const char* PROJECT_NAME = \"")
                .append(escape(projectJson.optString("projectName", config.getGameName())))
                .append("\";\n");
        sb.append("constexpr int WINDOW_WIDTH = ").append(config.getWidth()).append(";\n");
        sb.append("constexpr int WINDOW_HEIGHT = ").append(config.getHeight()).append(";\n");
        sb.append("constexpr bool WINDOW_FULLSCREEN = ").append(config.isFullscreen()).append(";\n\n");

        sb.append("struct EntityData {\n");
        sb.append("    const char* id;\n");
        sb.append("    const char* type;\n");
        sb.append("    const char* name;\n");
        sb.append("    double x;\n");
        sb.append("    double y;\n");
        sb.append("    int width;\n");
        sb.append("    int height;\n");
        sb.append("    const char* sprite;     // empty when none\n");
        sb.append("    int scriptCount;\n");
        sb.append("};\n\n");

        // Filename of the project's entry scene (e.g. "main.scene.json"), used to
        // emit a stable SCENE_MAIN alias decoupled from the scene's display name.
        String mainSceneFile = projectJson.optString("mainScene", "");
        String mainSymbol = null;

        List<String> sceneEntries = BuildIO.listZipEntries(request.getIgnisFile(), "scenes/", ".scene.json");
        Set<String> usedSymbols = new HashSet<>();
        for (String entryName : sceneEntries) {
            String sceneText = BuildIO.readZipEntryText(request.getIgnisFile(), entryName);
            if (sceneText == null) {
                continue;
            }
            JSONObject sceneJson = new JSONObject(sceneText);
            String sceneName = sceneJson.optString("sceneName", "Scene");
            String symbol = uniqueSymbol(sceneName, usedSymbols);

            // First scene is the default entry; an explicit mainScene match wins.
            if (mainSymbol == null) {
                mainSymbol = symbol;
            }
            if (!mainSceneFile.isEmpty() && entryName.endsWith(mainSceneFile)) {
                mainSymbol = symbol;
            }

            sb.append("// Scene: ").append(sceneName).append(" (").append(entryName).append(")\n");
            sb.append("constexpr EntityData ").append(symbol).append("[] = {\n");

            JSONArray entities = sceneJson.optJSONArray("entities");
            if (entities != null) {
                for (int i = 0; i < entities.length(); i++) {
                    JSONObject entity = entities.getJSONObject(i);
                    JSONObject position = entity.optJSONObject("position");
                    JSONObject size = entity.optJSONObject("size");
                    JSONArray scripts = entity.optJSONArray("scripts");
                    sb.append("    { \"").append(escape(entity.optString("id")))
                            .append("\", \"").append(escape(entity.optString("type")))
                            .append("\", \"").append(escape(entity.optString("name")))
                            .append("\", ").append(position != null ? position.optDouble("x", 0) : 0)
                            .append(", ").append(position != null ? position.optDouble("y", 0) : 0)
                            .append(", ").append(size != null ? size.optInt("width", 0) : 0)
                            .append(", ").append(size != null ? size.optInt("height", 0) : 0)
                            .append(", \"").append(escape(entity.optString("sprite", "")))
                            .append("\", ").append(scripts != null ? scripts.length() : 0)
                            .append(" },\n");
                }
            }
            sb.append("};\n");
            sb.append("constexpr int ").append(symbol).append("_COUNT = ")
                    .append(entities != null ? entities.length() : 0).append(";\n\n");
        }

        // Canonical entry-scene alias so main.cpp never depends on a scene's name.
        // Falls back to an empty scene when the project ships no scenes.
        sb.append("// Canonical entry scene (decoupled from scene display name)\n");
        if (mainSymbol != null) {
            sb.append("constexpr const EntityData* SCENE_MAIN = ").append(mainSymbol).append(";\n");
            sb.append("constexpr int SCENE_MAIN_COUNT = ").append(mainSymbol).append("_COUNT;\n\n");
        } else {
            sb.append("constexpr const EntityData* SCENE_MAIN = nullptr;\n");
            sb.append("constexpr int SCENE_MAIN_COUNT = 0;\n\n");
        }

        sb.append("} // namespace ignis\n");
        return sb.toString();
    }

    /** Builds a C++ identifier from a scene name, disambiguating collisions. */
    private static String uniqueSymbol(String sceneName, Set<String> used) {
        // The "SCENE_" prefix guarantees a valid identifier start; only an
        // all-symbol scene name would leave nothing after it.
        String suffixPart = sceneName.toUpperCase().replaceAll("[^A-Z0-9]", "_");
        String base = "SCENE_" + (suffixPart.isEmpty() ? "UNNAMED" : suffixPart);
        String symbol = base;
        int counter = 2;
        while (!used.add(symbol)) {
            symbol = base + "_" + counter++;
        }
        return symbol;
    }

    private static String escape(String value) {
        return value.replace("\\", "\\\\").replace("\"", "\\\"");
    }

    // ==================== PROJECT SKELETON TEMPLATES ====================

    private String cmakeLists(String gameName) {
        return "cmake_minimum_required(VERSION 3.16)\n"
                + "project(" + gameName + " CXX)\n\n"
                + "set(CMAKE_CXX_STANDARD 17)\n"
                + "set(CMAKE_CXX_STANDARD_REQUIRED ON)\n\n"
                + "add_executable(" + gameName + "\n"
                + "    src/main.cpp\n"
                + "    src/ignis_runtime.cpp\n"
                + ")\n\n"
                + "target_include_directories(" + gameName + " PRIVATE generated src)\n\n"
                + "# Console SDK integration:\n"
                + "# add_subdirectory(platform/<console>) once the proprietary SDK toolchain\n"
                + "# file is configured. See platform/<console>/README.md.\n";
    }

    private String runtimeHeader() {
        return "// Minimal portable runtime interface for exported Ignis projects.\n"
                + "// Console backends implement these hooks on top of their SDKs.\n"
                + "#pragma once\n\n"
                + "namespace ignis {\n\n"
                + "struct EntityData;\n\n"
                + "// Lifecycle hooks the platform backend must drive.\n"
                + "void runtime_init(const EntityData* entities, int count);\n"
                + "void runtime_tick(double deltaSeconds);\n"
                + "void runtime_render();\n"
                + "void runtime_shutdown();\n\n"
                + "} // namespace ignis\n";
    }

    private String runtimeSource() {
        return "#include \"ignis_runtime.hpp\"\n"
                + "#include \"scene_data.h\"\n"
                + "#include <cstdio>\n\n"
                + "namespace ignis {\n\n"
                + "namespace {\n"
                + "const EntityData* g_entities = nullptr;\n"
                + "int g_entityCount = 0;\n"
                + "}\n\n"
                + "void runtime_init(const EntityData* entities, int count) {\n"
                + "    g_entities = entities;\n"
                + "    g_entityCount = count;\n"
                + "    std::printf(\"[ignis] runtime initialized with %d entities\\n\", count);\n"
                + "}\n\n"
                + "void runtime_tick(double /*deltaSeconds*/) {\n"
                + "    // TODO: entity update + collision step (port of com.ignis.core.Game::tick)\n"
                + "}\n\n"
                + "void runtime_render() {\n"
                + "    // TODO: platform renderer (implemented by the console backend)\n"
                + "}\n\n"
                + "void runtime_shutdown() {\n"
                + "    std::printf(\"[ignis] runtime shutdown\\n\");\n"
                + "}\n\n"
                + "} // namespace ignis\n";
    }

    private String mainSource(String gameName) {
        return "// Portable entry point for " + gameName + ".\n"
                + "// Console targets replace this main with the SDK-required entry point\n"
                + "// (see platform/<console>/README.md) and keep the runtime_* calls.\n"
                + "#include \"ignis_runtime.hpp\"\n"
                + "#include \"scene_data.h\"\n\n"
                + "int main() {\n"
                + "    ignis::runtime_init(ignis::SCENE_MAIN, ignis::SCENE_MAIN_COUNT);\n"
                + "    // Platform backends own the real game loop; this skeleton runs one frame.\n"
                + "    ignis::runtime_tick(1.0 / 60.0);\n"
                + "    ignis::runtime_render();\n"
                + "    ignis::runtime_shutdown();\n"
                + "    return 0;\n"
                + "}\n";
    }

    private String platformReadme(BuildTarget target) {
        String sdk;
        switch (target) {
            case XBOX:
                sdk = "Microsoft GDK (Game Development Kit). Requires a registered developer "
                        + "account at https://developer.microsoft.com. Add the GDK toolchain file "
                        + "via -DCMAKE_TOOLCHAIN_FILE and implement runtime_render() over DirectX 12.";
                break;
            case PLAYSTATION:
                sdk = "PlayStation SDK (requires a licensed partner account at "
                        + "https://partners.playstation.net). Integrate the toolchain provided by "
                        + "the SDK and implement runtime_render() over the platform graphics API.";
                break;
            case NINTENDO_SWITCH:
            default:
                sdk = "Nintendo Dev Interface (requires a licensed developer account at "
                        + "https://developer.nintendo.com). Planned target - skeleton only.";
                break;
        }
        return "# " + target.getDisplayName() + " integration\n\n"
                + "This folder is the integration point between the exported portable core and the\n"
                + "proprietary console SDK, which cannot be redistributed with the engine.\n\n"
                + "SDK: " + sdk + "\n\n"
                + "Steps:\n"
                + "1. Install the SDK and its CMake toolchain.\n"
                + "2. Implement the runtime hooks (`runtime_render`, input, audio) in this folder.\n"
                + "3. Point CMake to the toolchain file and build.\n\n"
                + "The exported game content lives in `export/` and the generated scene data in\n"
                + "`generated/scene_data.h`.\n";
    }
}
